import bcrypt from "bcryptjs";
import { TorusGeometry } from "three";
const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      zipcode: "95192",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Apples",
      storeName: "Sprouts",
      price: 1.0,
      badges: [],
      thumbnail: "apple.jpg",
      slug: "apple",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Oranges",
      storeName: "Sprouts",
      price: 2,
      badges: [],
      thumbnail: "orange.jpg",
      slug: "orange",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Bananas",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "banana.jpg",
      slug: "banana",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Avacados",
      storeName: "Sprouts",
      price: 0.75,
      badges: [],
      thumbnail: "avacado.jpg",
      slug: "avacado",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Lemons",
      storeName: "Sprouts",
      price: 0.33,
      badges: [],
      thumbnail: "lemon.jpg",
      slug: "lemon",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Limes",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "lime.jpg",
      slug: "lime",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Strawberries",
      storeName: "Sprouts",
      price: 4.49,
      badges: [],
      thumbnail: "strawberry.jpg",
      slug: "strawberry",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Blueberries",
      storeName: "Sprouts",
      price: 3.99,
      badges: [],
      thumbnail: "blueberry.jpg",
      slug: "blueberry",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Pineapple",
      storeName: "Sprouts",
      price: 2.5,
      badges: [],
      thumbnail: "pineapple.jpg",
      slug: "pineapple",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Red Mangoes",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "redmango.jpg",
      slug: "red_mango",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Cantaloupe",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "cantaloupe.jpg",
      slug: "cantaloupe",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Grapes",
      storeName: "Sprouts",
      price: 3.84,
      badges: [],
      thumbnail: "grape.jpg",
      slug: "grapes",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Watermelon",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "watermelon.jpg",
      slug: "watermelon",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Pears",
      storeName: "Sprouts",
      price: 0.8,
      badges: [],
      thumbnail: "pear.jpg",
      slug: "pear",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Grapefruit",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "grapefruit.jpg",
      slug: "grapefruit",
      foodgroup: "fruits",
      perishable: true,
    },
    {
      name: "Cucumber",
      storeName: "Sprouts",
      price: 0.5,
      badges: [],
      thumbnail: "cucumber.jpg",
      slug: "cucumber",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Red Bell Peppers",
      storeName: "Sprouts",
      price: 1.5,
      badges: [],
      thumbnail: "redbellpepper.jpg",
      slug: "red_bell_pepper",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Broccoli",
      storeName: "Sprouts",
      price: 1.34,
      badges: [],
      thumbnail: "broccoli.jpg",
      slug: "broccoli",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Zucchini Squash",
      storeName: "Sprouts",
      price: 0.5,
      badges: [],
      thumbnail: "zucchini.jpg",
      slug: "zucchini",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Cilantro",
      storeName: "Sprouts",
      price: 0.5,
      badges: [],
      thumbnail: "cilantro.jpg",
      slug: "cilantro",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Yellow Onions",
      storeName: "Sprouts",
      price: 0.48,
      badges: [],
      thumbnail: "yellowonion.jpg",
      slug: "yellow_onion",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Green Bell Peppers",
      storeName: "Sprouts",
      price: 0.69,
      badges: [],
      thumbnail: "greenbellpepper.jpg",
      slug: "green_bell_peppers",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Red Onions",
      storeName: "Sprouts",
      price: 0.86,
      badges: [],
      thumbnail: "redonion.jpg",
      slug: "red_onion",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Green Onions",
      storeName: "Sprouts",
      price: 0.5,
      badges: [],
      thumbnail: "greenonion.jpg",
      slug: "green_onion",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Roma Tomatoes",
      storeName: "Sprouts",
      price: 0.25,
      badges: [],
      thumbnail: "tomato.jpg",
      slug: "tomato",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Celery",
      storeName: "Sprouts",
      price: 0.99,
      badges: [],
      thumbnail: "celery.jpg",
      slug: "celery",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Garlic",
      storeName: "Sprouts",
      price: 0.5,
      badges: [],
      thumbnail: "garlic.jpg",
      slug: "garlic",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Green Beans",
      storeName: "Sprouts",
      price: 1.79,
      badges: [],
      thumbnail: "greenbeans.jpg",
      slug: "green_beans",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Jewel Yam",
      storeName: "Sprouts",
      price: 0.88,
      badges: [],
      thumbnail: "yam.jpg",
      slug: "jewel_yam",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Russet Potatoes",
      storeName: "Sprouts",
      price: 0.75,
      badges: [],
      thumbnail: "potato.jpg",
      slug: "russet_potatoes",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Sweet Corn",
      storeName: "Sprouts",
      price: 0.99,
      badges: [],
      thumbnail: "corn.jpg",
      slug: "sweet_corn",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Carrots",
      storeName: "Sprouts",
      price: 0.45,
      badges: [],
      thumbnail: "carrot.jpg",
      slug: "carrot",
      foodgroup: "vegetables",
      perishable: true,
    },
    {
      name: "Apple Juice",
      storeName: "Sprouts",
      price: 4.29,
      badges: [],
      thumbnail: "applejuice.jpg",
      slug: "apple_juice",
      foodgroup: "beverages",
      perishable: true,
    },
    {
      name: "Grape Juice",
      storeName: "Sprouts",
      price: 4.29,
      badges: [],
      thumbnail: "grapejuice.jpg",
      slug: "grape_juice",
      foodgroup: "beverages",
      perishable: true,
    },
    {
      name: "Wagyu",
      storeName: "Sprouts",
      price: 28.49,
      badges: ["Sponsored"],
      thumbnail: "wagyu.jpg",
      slug: "wagyu",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Ground Beef",
      storeName: "Sprouts",
      price: 6.99,
      badges: [],
      thumbnail: "groundbeef.jpg",
      slug: "ground_beef",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Ground Turkey",
      storeName: "Sprouts",
      price: 5.99,
      badges: ["Sponsored"],
      thumbnail: "wagyu.jpg",
      slug: "wagyu",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Chicken Breast",
      storeName: "Sprouts",
      price: 12.49,
      badges: ["Sponsored"],
      thumbnail: "chicken.jpeg",
      slug: "chicken_breast",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Italian Chicken Sausage",
      storeName: "Sprouts",
      price: 9.99,
      badges: [],
      thumbnail: "chickensausage.jpg",
      slug: "italian_chicken_sausage",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Pork Breakfast Sausage",
      storeName: "Sprouts",
      price: 7.99,
      badges: ["Sponsored"],
      thumbnail: "porksausage.jpg",
      slug: "pork_sausage",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Atlantic Salmon Fillet",
      storeName: "Sprouts",
      price: 10.99,
      badges: [],
      thumbnail: "salmon.jpg",
      slug: "atlantic_salmon",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Tilapia Fillet",
      storeName: "Sprouts",
      price: 8.99,
      badges: [],
      thumbnail: "tilapia.jpg",
      slug: "tilapia",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "13 Large Shrimp Raw",
      storeName: "Sprouts",
      price: 12.99,
      badges: [],
      thumbnail: "shrimp.jpg",
      slug: "shrimp",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "Applewood Smoked Bacon",
      storeName: "Sprouts",
      price: 8.99,
      badges: [],
      thumbnail: "bacon.jpg",
      slug: "applewood_bacon",
      foodgroup: "meat",
      perishable: true,
    },
    {
      name: "2% Reduced Fat Milk",
      storeName: "Sprouts",
      price: 5.99,
      badges: [],
      thumbnail: "milk.jpg",
      slug: "milk",
      foodgroup: "dairy",
      perishable: true,
    },
    {
      name: "Unsalted Butter",
      storeName: "Sprouts",
      price: 3.49,
      badges: [],
      thumbnail: "butter.jpg",
      slug: "butter",
      foodgroup: "dairy",
      perishable: true,
    },
    {
      name: "Large Brown Eggs",
      storeName: "Sprouts",
      price: 2.79,
      badges: [],
      thumbnail: "eggs.jpg",
      slug: "eggs",
      foodgroup: "dairy",
      perishable: true,
    },
    {
      name: "Greek Gods Plain Greek Yogurt",
      storeName: "Sprouts",
      price: 5.49,
      badges: [],
      thumbnail: "greekyogurt.jpg",
      slug: "greek_yogurt",
      foodgroup: "dairy",
      perishable: true,
    },
    {
      name: "French Bread",
      storeName: "Sprouts",
      price: 1.99,
      badges: [],
      thumbnail: "frenchbread.jpg",
      slug: "french_bread",
      foodgroup: "grains",
      perishable: true,
    },
    {
      name: "Rolled Oats 1lb",
      storeName: "Sprouts",
      price: 1.39,
      badges: [],
      thumbnail: "oats.jpg",
      slug: "rolled_oats",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "White Jasmine Rice 1lb",
      storeName: "Sprouts",
      price: 1.99,
      badges: [],
      thumbnail: "jasminerice.jpg",
      slug: "jasmine_rice",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "Brown Long Grain Rice 1lb",
      storeName: "Sprouts",
      price: 1.59,
      badges: [],
      thumbnail: "brownlongrice.jpg",
      slug: "brown_long_grain_rice",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "White Short Grain Rice 1lb",
      storeName: "Sprouts",
      price: 1.59,
      badges: [],
      thumbnail: "whiteshortrice.jpg",
      slug: "white_short_grain_rice",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "Pinto Beans 1lb",
      storeName: "Sprouts",
      price: 2.29,
      badges: [],
      thumbnail: "pintobeans.jpg",
      slug: "pinto_beans",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "Whole Grain Bread",
      storeName: "Sprouts",
      price: 6.79,
      badges: [],
      thumbnail: "wholegrainbread.jpg",
      slug: "whole_grain_bread",
      foodgroup: "grains",
      perishable: true,
    },
    {
      name: "White Quinoa 1lb",
      storeName: "Sprouts",
      price: 4.49,
      badges: [],
      thumbnail: "whitequinoa.jpg",
      slug: "white_quinoa",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "Baguette",
      storeName: "Sprouts",
      price: 1.89,
      badges: [],
      thumbnail: "baguette.jpg",
      slug: "baguette",
      foodgroup: "grains",
      perishable: true,
    },
    {
      name: "Honey Almond Granola",
      storeName: "Sprouts",
      price: 3.99,
      badges: [],
      thumbnail: "honeyalmondgranola.jpg",
      slug: "honey_almond_granola",
      foodgroup: "grains",
      perishable: false,
    },
    {
      name: "Raw Almonds 1lb",
      storeName: "Sprouts",
      price: 6.99,
      badges: [],
      thumbnail: "almonds.jpg",
      slug: "almonds",
      foodgroup: "other",
      perishable: false,
    },
    {
      name: "12 Chocolate Chip Cookies",
      storeName: "Sprouts",
      price: 4.29,
      badges: [],
      thumbnail: "chocolatecookies.jpg",
      slug: "chocolate_chip_cookies",
      foodgroup: "desserts",
      perishable: false,
    },
    {
      name: "Chocolate Chip Muffins",
      storeName: "Sprouts",
      price: 4.29,
      badges: [],
      thumbnail: "chocolatemuffins.jpg",
      slug: "chocolate_chip_muffins",
      foodgroup: "desserts",
      perishable: false,
    },
    {
      name: "Cinnamon Rolls",
      storeName: "Sprouts",
      price: 4.99,
      badges: [],
      thumbnail: "cinnamonrolls.jpg",
      slug: "cinnamon_rolls",
      foodgroup: "desserts",
      perishable: false,
    },
    {
      name: "3 Pack Croissants",
      storeName: "Sprouts",
      price: 3.49,
      badges: [],
      thumbnail: "croissants.jpg",
      slug: "croissants",
      foodgroup: "desserts",
      perishable: false,
    },
    {
      name: "Almond Flour 1lb",
      storeName: "Sprouts",
      price: 7.99,
      badges: [""],
      thumbnail: "almondflour.jpg",
      slug: "almond_flour",
      foodgroup: "other",
      perishable: false,
    },
    {
      name: "Unsalted Creamy Peanut Butter",
      storeName: "Sprouts",
      price: 3.39,
      badges: [],
      thumbnail: "peanutbutter.jpg",
      slug: "creamy_peanut_butter",
      foodgroup: "oils/fats",
      perishable: false,
    },
    {
      name: "Clover Honey",
      storeName: "Sprouts",
      price: 6.39,
      badges: [],
      thumbnail: "cloverhoney.jpg",
      slug: "clover_honey",
      foodgroup: "other",
      perishable: false,
    },
  ],
  pantry: [
    {
      email: "admin@example.com",
      items: [
        {
          name: "apple",
          thumbnail: "apple.jpg",
          quantity: 2,
          foodgroup: "fruits",
          perishable: true,
        },
        {
          name: "wagyu",
          thumbnail: "wagyu.jpg",
          quantity: 1,
          foodgroup: "meat",
          perishable: true,
        },
        {
          name: "eggs",
          thumbnail: "eggs.jpg",
          quantity: 6,
          foodgroup: "dairy",
          perishable: true,
        },
        {
          name: "avacado",
          thumbnail: "avacado.jpg",
          quantity: 2,
          foodgroup: "fruits",
          perishable: true,
        },
        {
          name: "baguette",
          thumbnail: "baguette.jpg",
          quantity: 1,
          foodgroup: "grains",
          perishable: true,
        },
        {
          name: "lemon",
          thumbnail: "lemon.jpg",
          quantity: 4,
          foodgroup: "fruits",
          perishable: true,
        },
        {
          name: "butter",
          thumbnail: "butter.jpg",
          quantity: 4,
          foodgroup: "dairy",
          perishable: true,
        },
      ],
    },
  ],
};

export default data;
